# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a13961c145f9a7737a63e775723339efd4ca414a09d387a7db690cb5f68d88937512fab2eb82fa1fc329cdbad607c9ea7516304b8918ea322b6a9c7cea05eee

test:
  secret_key_base: 84af3e2fb8094976b4a94543e1619a698fdd95fbcb92a9ff7ff6d629eb3909c57f3cb9c68d6f4c81754ec06c2ab9c9825acb0641469129328780c53347905fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
